name: Build Docker Image without Push

on:
  push:
    branches: [ muratams/test-workflow ]
    paths:
      - '.github/workflows/build-docker-image.yaml'
      - '**'
      - '!docker/home/**'
      - '!docker/*.sh'
      - '!docker/timezone/**'
      - '!docker/uid/**'

jobs:
  build-free-space-people:
    uses: ./.github/workflows/build-free-space.yaml
    with:
      prebuild-name: people
      build-name: people
      push-name: people
      tag-name: ros2-dev-latest
  
  build-host-ws:
    uses: ./.github/workflows/build-host-ws.yaml